/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: [
    "./index.html",
    "./code.html",
    "./src/**/*.{js,jsx,ts,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "secondary-fixed": "#c3f09b",
        "on-primary": "#ffffff",
        "on-secondary": "#ffffff",
        tertiary: "#74532f",
        "surface-container-high": "#eae7e7",
        "tertiary-fixed": "#ffdcbc",
        outline: "#8c716d",
        "secondary-fixed-dim": "#a7d382",
        "outline-variant": "#e0bfbb",
        "inverse-on-surface": "#f3f0ef",
        "error-container": "#ffdad6",
        "on-tertiary-container": "#fff7f2",
        "primary-container": "#c6463d",
        "on-primary-container": "#fff6f5",
        "on-secondary-fixed": "#0c2000",
        "on-surface": "#1c1b1b",
        "on-primary-fixed-variant": "#8a1a17",
        "on-primary-fixed": "#410002",
        error: "#ba1a1a",
        "surface-dim": "#dcd9d9",
        "on-error": "#ffffff",
        surface: "#fcf9f8",
        background: "#fcf9f8",
        "secondary-container": "#c0ed98",
        "inverse-primary": "#ffb4ab",
        "surface-variant": "#e5e2e1",
        primary: "#a52e28",
        "surface-container-low": "#f6f3f2",
        "inverse-surface": "#313030",
        "on-secondary-container": "#476d27",
        "tertiary-container": "#8f6b45",
        "surface-container": "#f0eded",
        "surface-bright": "#fcf9f8",
        "surface-tint": "#ac332c",
        "on-tertiary": "#ffffff",
        "primary-fixed": "#ffdad6",
        "on-secondary-fixed-variant": "#2c500c",
        "tertiary-fixed-dim": "#ebbe92",
        "on-tertiary-fixed-variant": "#5f401e",
        "on-tertiary-fixed": "#2c1700",
        secondary: "#436824",
        "primary-fixed-dim": "#ffb4ab",
        "surface-container-highest": "#e5e2e1",
        "surface-container-lowest": "#ffffff",
        "on-surface-variant": "#58413e",
        "on-error-container": "#93000a",
        "on-background": "#1c1b1b",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      fontFamily: {
        headline: ["Space Grotesk"],
        body: ["Be Vietnam Pro"],
        label: ["Space Grotesk"],
      },
    },
  },
  plugins: [],
};
